---
- name: Installer firewalld
  yum:
    name: firewalld
    state: present

- name: Ouvrir le port 8080
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
  notify: Recharger firewalld
