
---
- name: Installer httpd
  yum:
    name: httpd
    state: present

- name: Modifier le port d'écoute de 80 à 8080
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 80'
    line: 'Listen 8080'
    state: present
  notify: Redémarrer httpd

