---
- name: Inclure les variables utilisateur
  include_vars:
    file: user.txt

- name: Ajouter l'utilisateur dev1
  user:
    name: dev1
    password: "{{ vagrant | string | password_hash('sha512') }}"
